#spring:
#  application:
#    name: ApiGateway
#  cloud.gateway:
#    discovery:
#      locator:
#        enabled: true
#        lowerCaseServiceId: true
#    routes:
#      - id: producer
#        uri: lb://producer
#        predicates:
#          - Path=/producer/**
#      - id: comsumer
#        uri: lb://comsumer
#        predicates:
#          - Path=/consumer/**
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#
#server:
#  port: 8089